migration-client/wso2-api-migration-client/src/assembly/dist.xml, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom210.java
This PR will move api.rxt to migration-resources folder
=> Move api.rxt to migration-resources folder

apim-migration-testing-tool/Python/ApiMangerConfigUtil/xml_file_change.py, apim-migration-testing-tool/Python/DbUtil/run_sql_queries.py, apim-migration-testing-tool/data/API-M_3.1.0/oracle/deployment.toml
=> Fix oracle db (12.2) related issues

migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/APIMMigrationService.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom110to200.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom18to19.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom19to110.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom200.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom200to210.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom210.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom310.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrationClient.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/ScopeRoleMappingPopulationClient.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/dao/APIMgtDAO.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/dto/ResourceScopeMappingDTO.java
> Add migration logic for migrating scopes when migrating from 310 to 320
=> Add scope migration from 310 to 320

migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/dao/SharedDAO.java
fixes https://github.com/wso2/product-apim/issues/8594
=> Fix scope role mapping client error

migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom310.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/dao/APIMgtDAO.java
Fixing https://github.com/wso2/product-apim/issues/8496
=> Fix scope migration tenant issue

migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/APIMMigrationService.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom110to200.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom18to19.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom19to110.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom200.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom200to210.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom210.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom310.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrationClient.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/ScopeRoleMappingPopulationClient.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/sp_migration/APIMStatMigrationClient.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/dao/APIMgtDAO.java
Fix https://github.com/wso2/product-apim/issues/8545
=> Fix Application Key generation page issue

migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/APIMMigrationService.java
Poulate app info field while migrating to 3.2 from 2.x
=> Run application grant types migration for 2.X to 3.2 migrations

migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/APIMMigrationService.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom110to200.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom18to19.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom19to110.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom200.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom200to210.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom210.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom310.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrationClient.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/ScopeRoleMappingPopulationClient.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/sp_migration/APIMStatMigrationClient.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/dao/APIMgtDAO.java
Fixes https://github.com/wso2/product-apim/issues/8826
In 3.1.0 the property key 'tokenType' in 'IDN_OUDC_PROPERTY' is set to default even if the TOKEN_TYPE in AM_APPLICATION for the corresponding app is JWT. This causes issues in 3.2.0 as this field is taken into consideration in token generation flow. Therefore we need to update the 'tokenType' property key for JWT type applications to JWT.
> …
=> Add updateTokenTypeToJWT section in spMigration back to the client

migration-client/wso2-api-migration-client/src/assembly/dist.xml, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/APIMMigrationService.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom310.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrationClientBase.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/Constants.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/RegistryService.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/RegistryServiceImpl.java, migration-client/wso2-api-migration-client/src/main/resources/310to320Migration/rxts/api.rxt
Fixes https://github.com/wso2/product-apim/issues/8848 …
=> Add 'enableStore' rxt field to migrated APIs

migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/APIMMigrationService.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom110to200.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom18to19.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom19to110.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom200.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom200to210.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom210.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom310.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrationClient.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/ScopeRoleMappingPopulationClient.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/sp_migration/APIMStatMigrationClient.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/Constants.java
Fixes https://github.com/wso2/product-apim/issues/8946  …
=> Update old scopes in tenant-conf.json with Internal creator and publisher role mappings

migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/APIMMigrationService.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom200.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom210.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom310.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrationClientBase.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/RegistryServiceImpl.java
This PR fixes issue with tenant API categories.
Fixes below issue : 
In a migrated setup login to tenant admin portal and create an API category. Then attach this to a tenant API. Go to devportal and expand api category listing for tenant. No api will be shown.
Fix : 
Need to add an rxt migration.
> Type “Sent” when you have provided new/updated certification questions, plus four answers …
=> Fix api categories issue in tenants

migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/ScopeRoleMappingPopulationClient.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/Constants.java
This PR will add fixes for,
[1]. https://github.com/wso2/product-apim/issues/9000
[2]. https://github.com/wso2/product-apim/issues/9057
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc …
=> Fix Issues with tenant-conf.json

migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/APIMMigrationService.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrationClient.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/ScopeRoleMappingPopulationClient.java
In case a scope's role mappings had been updated over the versions, we need to add the correct scope mapping in the tenant-conf.json.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc …
=> Add migration for existing scopes in tenant-conf.json

migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrationExecutor.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/_200Specific/ResourceModifier200.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/SynapseUtil.java
This PR fixes issues in 1.10 to 3.2 migration. …
=> Fix issues in 1.10 migration client

migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/APIMMigrationService.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom18to19.java
Fixes: https://github.com/wso2-extensions/apim-migration-resources/pull/9#discussion_r566784034
Fixes: https://github.com/wso2-extensions/apim-migration-resources/pull/9#discussion_r566787074
Fixes: https://github.com/wso2-extensions/apim-migration-resources/pull/9#discussion_r566787358
Fixes: https://github.com/wso2-extensions/apim-migration-resources/pull/9#discussion_r566787849
=> [3.1.0] Fixing reviewed comments

migration-client/wso2-api-migration-client/pom.xml, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/APIMMigrationService.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom110to200.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom320.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrationClientFactory.java, migration-client/wso2-api-migration-client/src/test/java/org/wso2/carbon/apimgt/migration/client/MigrationClientFactoryTest.java
Update dependencies
Create Common Migration Impl Class for 3.2 to 4.0 migration
=> Adding initial 4.0 migration client changes

migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/APIMMigrationService.java
=> Comment out 4.0 related migration code

migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/RegistryServiceImpl.java
=> Fix check done to see if overview type is null

migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/RegistryServiceImpl.java
Reverting https://github.com/wso2-extensions/apim-migration-resources/commit/7035400dd221027dea3ee9d59df751d101eb71c1 and https://github.com/wso2-extensions/apim-migration-resources/commit/56c7848d17b5a8c26a0c1804d741a0a578feb6b0
=> [3.2.0] Reverting 2 commits

migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/sp_migration/DBManagerImpl.java
=> Fixing and Format apiCreatorTenantDomain logic

migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/RegistryServiceImpl.java
=> Add null string check for overview type

migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/APIMMigrationService.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom110to200.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom18to19.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom19to110.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom200.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom200to210.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom210.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom310.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom320.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrationClient.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/ScopeRoleMappingPopulationClient.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/sp_migration/APIMStatMigrationClient.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/dao/APIMgtDAO.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/Constants.java
Removing functions related to Cross Tenant API Subscription from Migration Client
Fixes: https://github.com/wso2/product-apim/issues/10231
Removing the changes introduced in https://github.com/wso2-extensions/apim-migration-resources/pull/55
=> Removing Functions Related to Cross Tenant API Subscriptions

migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/APIMMigrationService.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom320.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/dao/APIMgtDAO.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/RegistryServiceImpl.java
Adding Websocket API Migration
Fixes https://github.com/wso2/product-apim/issues/10206
Fixes https://github.com/wso2/product-apim/issues/10083
=> Adding Websocket API Migration changes

migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/dao/APIMgtDAO.java
$subject
MG Labels are removed from APIM 4.0.0 (9.0.71-SNAPSHOT)
```xml
<carbon.apimgt.version>9.0.71-SNAPSHOT</carbon.apimgt.version>
```
wso2/carbon-apimgt#10010
fix https://github.com/wso2/product-apim/issues/10253
=> Drop table 'AM_LABELS' and 'AM_LABEL_URLS'

migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/APIMMigrationService.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom200.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom400.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrationClientBase.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/ScopeRoleMappingPopulationClient.java
=> add tenant-config migration from product to migration client

migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom19to110.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom320.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/dto/APIInfoDTO.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/Constants.java
> fix migration client as per the code refactoring happened in carbon-apimgt
=> fix build breaks

migration-client/wso2-api-migration-client/pom.xml
Upgrading dependencies to fix build failure
=> Upgrading dependencies to fix build failure

migration-client/wso2-api-migration-client/pom.xml, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/APIMMigrationService.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom400.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrationClientBase.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/dao/APIMgtDAO.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/Constants.java, migration-client/wso2-api-migration-client/src/main/resources/400to410Migration.rxts/api.rxt
=> Improving 400-410 migration flow

migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/dao/APIMgtDAO.java
>  Fix the sql query to update the table am_application(the existing query doesnt work with postgre sql)
>Improve error handling, currently no errors are thrown even if there are sql exceptions. DAO methods have been modified to throw errors when there are issues while performing db operations
=> Fix SQL level issues

components/migration-client/wso2-api-migration-client/src/main/resources/build-migration-script.sh
=> Adding issues in script

components/migration-client/wso2-api-migration-client/src/main/resources/build-migration-script.sh
=> Fixing issue in scripts

components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom320.java
=> Adding artifactPath check during retrieve artifact

components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/APIMMigrationService.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom320.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom400.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrationClientBase.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/dao/APIMgtDAO.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/Constants.java
$Subject & fixing issue in product flow …
=> Refactoring 3.2.0 migration flow

migration-client/wso2-api-migration-client/pom.xml, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom320.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/dao/APIMgtDAO.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/dto/KeyManagerConfigurationDTO.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/dto/TokenHandlingDTO.java
Adding Default KM for Tenants to solve the UUID becoming null issue
=> Adding Default KM for Tenants

migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom320.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrationClientBase.java
Fixing fault sequence issue and inactive tenant issue
=> Fixing fault sequence issue

components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/APIMMigrationClient.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/ValidationHandler.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/utils/Utils.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/utils/UtilsFactory.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/utils/V260Utils.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/utils/V300Utils.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/utils/V310Utils.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/utils/V320Utils.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/utils/V400Utils.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/validators/V410Validator.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/validators/Validator.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/validators/ValidatorFactory.java
This PR adds validators and API definition validation methods.
=> Add validators and API definition validation methods

components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/dao/APIMgtDAO.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/utils/Utils.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/utils/V400Utils.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/validators/V410Validator.java
This PR adds revision checks when retrieving the API definitions for APIM 4.0.0 validation utils.
=> Add revision check when retrieving API definition path

components/migration-client/wso2-api-migration-client/pom.xml, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/v400/ImportExport/ExportUtils.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/v400/ImportExport/ImportExportAPI.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/v400/ImportExport/ImportExportAPIServiceImpl.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/v400/V400RegistryResourceMigrator.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/v400/dao/ApiMgtDAO.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/v400/model/APIManager.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/v400/model/APIProvider.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/v400/model/APIProviderImpl.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/v400/model/AbstractAPIManager.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/APIUtil.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/Constants.java
=> adding Client refactor utills 

components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/internal/APIMMigrationServiceComponent.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/client/V410Migration.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/APIUtil.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/ExtendedAPIMConfigServiceImpl.java
Engaging extended config service impl with registry based implementation.
=> Adding config service extended implementation

components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/commonMigrators/PostDBScriptMigrator.java
Fixes https://github.com/wso2-extensions/apim-migration-resources/issues/184
Fixes https://github.com/wso2-extensions/apim-migration-resources/issues/184
Since the correct sql file path has to be constructed using the dbtype information, isPathProvided parameter is set to false in the AMDBUtil.runSQLScript from the PostDBScriptMigrator.
> Type “Sent” when you have provided new/updated …
=> Fixes FileNotFoundException during PostDBScriptMigrator

components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/internal/APIMMigrationServiceComponent.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/internal/ServiceHolder.java
Fixes https://github.com/wso2-extensions/apim-migration-resources/issues/188
* adds @scr.reference for indexLoader
* Fixes static variable initialization issue in ServiceHolder. setIndexLoaderService
> Type “Sent” when you have provided new/updated certification questions, plus four answers …
=> [4.1.0-migration] Fix NPE while loading tenant registry

components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/internal/APIMMigrationServiceComponent.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/internal/ServiceHolder.java
Fixes https://github.com/wso2-extensions/apim-migration-resources/issues/191 …
=> [4.1.0-migration] Fix issues in ServiceHolder and APIMMigrationServiceComponent

components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/APIUtil.java
=> Fixing APIUtil Version Issue

components/migration-client/wso2-api-migration-client/pom.xml, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/Utility.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/v410/V410DBDataMigrator.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/Constants.java, pom.xml
This PR,
* Fixes syncing issue in tenant-conf
* Points to carbon-apimgt 4.1.0 instead of master
> Link to the PR for changes to …
=> Fixes issue in tenant-conf migration

components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/v400/dao/ApiMgtDAO.java
=> fixed sql issue in addAPIProductRevision

components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/v400/V400RegistryResourceMigrator.java
=> [4.1.0 Migration] Fix issue while searching for client certs in API Product

components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom400.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/dao/APIMgtDAO.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/v410/V410RegistryResourceMigrator.java
=> [4.1.0 Migration] Improve migration logs

components/migration-client/wso2-api-migration-client/src/main/resources/pre-migration-scripts/migration-3.2.0_to_4.0.0/oracle.sql, components/migration-scripts/migration-3.2.0_to_4.0.0/oracle.sql
=> Fixing Oracle DB Migration Scripts 3.2 to 4.0

components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/APIMMigrationClient.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/v400/V400RegistryResourceMigrator.java, components/migration-client/wso2-api-migration-client/src/main/resources/pre-migration-scripts/migration-3.1.0_to_3.2.0/postgresql.sql, components/migration-scripts/migration-3.1.0_to_3.2.0/postgresql.sql
=> Fixing issues in migration client

components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/Utility.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/v410/V410ScopeMigrator.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/Constants.java
This PR,
* Remove isMigrated check on tenant-conf.json Meta info as it was used in previous on the migration and not needed now.
* Syncs missing EnableRecommendation config in 4.1.0 migrations below 3.0.0.
* Renames Utility.migrateTenantConfScopes as this method now focuses on migrating content in tenant-conf.json as opposed to just syncing REAT API scope mappings.
related carbon-apimgt PR : https://github.com/wso2-support/carbon-apimgt/pull/5162
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is …
=> [4.1.0 migration] Fix tenant-conf syncing issues in 3.0.0 to 4.1.0 migration

components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/Constants.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/RegistryServiceImpl.java
- Migrated SOAP APIs from 2.6.0 still have the type field set as HTTP. This PR fixes it.
- Sets API Overview Type of migrated SOAP APIs as "SOAP"
- Checks whether the overview_wsdl is populated, this will be populated for both SOAP and SOAPTOREST type APIs
- if overview_wsdl is populated, based on existence of soap_to_rest resources decides whether the API is SOAP of SOAPTOREST
- if soap_to_rest exists -> SOAPTOREST
- if soap_to_rest  does not exist -> SOAP
- Based on above check updates overview_type of API artifact.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why …
=> [4.1.0 migration] Fix API Overview Type update in migrated SOAP APIs

components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/Constants.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/utils/V260Utils.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/validators/Validator.java
- Fixes wsdl pre-validation step for SOAP and SOAPTOREST from 2.6.0
- Pre-validation step is executed before running the APIM migration client. Hence the 2.6.0 SOAP and SOAPTOREST APIs would still have their type set as HTTP.
- Due to that WSDL validation for those APIs are skipped.
- As the fix, added a util method to figure out correct API Type based on overview_wsdl field and soap_to_rest registry resource. (Same logic used in PR https://github.com/wso2-extensions/apim-migration-resources/pull/214)
> Link(s) to product documentation that addresses …
=> [4.1.0 migration] Check SOAP API validation in 2.6.0-4.1.0 pre validation step

components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/v400/V400RegistryResourceMigrator.java
=> Start/Close Tenant flows properly

components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/client/V320Migration.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/commonMigrators/RegistryResourceMigrator.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/RegistryService.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/RegistryServiceImpl.java
Fixes https://github.com/wso2-extensions/apim-migration-resources/issues/227 …
=> [4.1.0 Migration] Fix property visibility issue after migration

components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/dao/APIMgtDAO.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/v400/V400DBDataMigrator.java
=> Adding a missing log update UUID And Status

components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/v400/dao/ApiMgtDAO.java
Fixes https://github.com/wso2-extensions/apim-migration-resources/issues/231
Removed references to `PROVIDER` column in v400 APIMgtDAO class since PROVIDER column is not available in APIM 4.0.0.
> Type “Sent” when you have provided new/updated certification questions, plus four answers for …
=> [4.1.0 Migration] Fix issue with PROVIDER column in AM_GATEWAY_ENVIRONMENT table

migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrationClientBase.java
Resovles: https://github.com/wso2-enterprise/wso2-apim-internal/issues/263 …
=> Fix issue in getTenantsArray method

migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/APIMMigrationService.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom18to19.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom19to110.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom200.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom200to210.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom210.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom310.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom320.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrationClient.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/ScopeRoleMappingPopulationClient.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/sp_migration/APIMStatMigrationClient.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/RegistryService.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/RegistryServiceImpl.java
Fixes https://github.com/wso2-extensions/apim-migration-resources/issues/227
Ports below PRs to 4.0.0 branch
[1]. https://github.com/wso2-extensions/apim-migration-resources/pull/109
[2]. https://github.com/wso2-extensions/apim-migration-resources/commit/794a67ba50ced5cf4d19c4ed2a88ef75ea393067 
> Brief description of the new feature or bug fix as it will appear in the …
=> [4.0.0] Fix API Property visibility issue

migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/Constants.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/RegistryServiceImpl.java
Ports https://github.com/wso2-extensions/apim-migration-resources/pull/214 …
=> [4.0.0] Fix API Overview Type update in migrated SOAP APIs

migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/APIMMigrationService.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom18to19.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom19to110.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom200.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom200to210.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom210.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom310.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom320.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrationClient.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/ScopeRoleMappingPopulationClient.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/sp_migration/APIMStatMigrationClient.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/dao/APIMgtDAO.java
Ports the fix in https://github.com/wso2-extensions/apim-migration-resources/pull/212
> Link to the PR for changes to the …
=> [4.0.0] Update API_TYPE in DB

migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/APIMMigrationService.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/IdentityScopeMigration.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom18to19.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom19to110.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom200.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom200to210.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom310.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom320.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateUUIDToDB.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrationClientBase.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrationDBCreator.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrationExecutor.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/ScopeRoleMappingPopulationClient.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/sp_migration/DBManagerImpl.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/dao/APIMgtDAO.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/dao/SharedDAO.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/RegistryServiceImpl.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/ResourceUtil.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/StatDBUtil.java
=> [4.0.0] Add 4.0.0 migration log improvements

migration-client/wso2-api-migration-client/pom.xml, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/APIMMigrationService.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/dao/APIMgtDAO.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/Constants.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/ValidationHandler.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/dao/ApiMgtDAO.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/utils/Utility.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/utils/Utils.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/utils/UtilsFactory.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/utils/V210Utils.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/utils/V220Utils.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/utils/V250Utils.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/utils/V260Utils.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/utils/V300Utils.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/utils/V310Utils.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/utils/V320Utils.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/utils/V400Utils.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/validators/V400Validator.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/validators/Validator.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/validators/ValidatorFactory.java
>  The PR adds the pre validation capability to 4.0.0 migration client which enables to pre validate certain artifacts like swagger files prior to the migration of 4.0.0.
=> Add Pre validation logic to 4.0.0 migration

migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom320.java
Fixes https://github.com/wso2-extensions/apim-migration-resources/issues/243 …
=> [4.0.0] Fix super tenant fault sequences not getting updated

migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom320.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/Constants.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/utils/Utils.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/validators/V400Validator.java
This PR fixes the issue where APIs created using WSDL Zip archives are migrated improperly. When it is a zip file, we cannot download the zip through the WSDL Definition view page.
This happens because the zip file in `/apimgt/applicationdata/wsdls/archives/` is not added under the relevant API according to the new architecture.
> Brief description of the new feature or …
=> [4.0.0] Fix migrating APIs created using WSDL zip archives

components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/v400/V400RegistryResourceMigrator.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/utils/Utils.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/validators/V410Validator.java
This PR fixes the following.
1. Fix migrating APIs created using WSDL zip archives
2. Add getURITemplates call to swagger pre validation
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc …
=> Add migration client fixes

components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/validators/V410Validator.java
This PR modifies a comment in the validator. …
=> Modify comment in the 4.1.0 validator

components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/validators/V410Validator.java
Reverts wso2-extensions/apim-migration-resources#248
=> Revert "Modify comment in the 4.1.0 validator"

migration-client/wso2-api-migration-client/pom.xml
This PR adds HEAD tag in scm url to fix build failure in jenkins build for migration client.
> Link to the PR for changes to the …
=> Add HEAD tag for scm none url

migration-client/wso2-api-migration-client/buildNumber.properties, migration-client/wso2-api-migration-client/pom.xml
This PR removes the build number based building of the migration client in APIM 4.0.0. Reverting [1].
[1] https://github.com/wso2-support/product-apim/commit/eaba4a3b153ad0a5187e813e82e3cc2573058b72
> Link(s) to product documentation that addresses the changes of this PR. If no doc …
=> Remove build number change

migration-client/wso2-api-migration-client/pom.xml
This PR adds the scm url to facilitate automated tag creation for 4.0.0 build.
> Link to the PR for changes to the training …
=> Add scm url to pom

migration-client/wso2-api-migration-client/src/test/java/org/wso2/carbon/apimgt/migration/client/MigrationClientFactoryTest.java
Temporarily commenting out test cases that are failing. …
=> comment tests temporarily

components/migration-client/wso2-api-migration-client/README.md, components/migration-client/wso2-api-migration-client/pom.xml, pom.xml
This PR updates migration client version to 4.2.0. …
=> Update migration client version to 4.2.0

migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/APIMMigrationService.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom320.java
This PR improves APIM Revision Related Migration to continue on error.
Addresses issue in https://github.com/wso2/api-manager/issues/616
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc …
=> [4.0.0] Improve APIM Revision Related Migration to continue on error

migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/APIMMigrationService.java
Fixes https://github.com/wso2/api-manager/issues/629
- Copy certificate content to DB before proceeding to revision related migration.
Error was due to running the revision related migration prior to EP certificate migration. During the revision related migration, when exporting an API with EP certs, it tries to fetch certificate content from the DB, but since the certificate migration is yet to be executed, this CERTIFICATE column of AM_CERTIFICATE_METADATA is empty leading to the error scenario.
Fixed the issue by running the EP certificate migration(which copies certificate content as a blob to DB) before revision related migration step.
> Link(s) …
=> [4.0.0] Execute certificate migration before revision related migration

migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/APIMMigrationService.java
Fixes https://github.com/wso2/api-manager/issues/629
- Copy certificate content to DB before proceeding to revision related migration.
Error was due to running the revision related migration prior to EP certificate migration. During the revision related migration, when exporting an API with EP certs, it tries to fetch certificate content from the DB, but since the certificate migration is yet to be executed, this CERTIFICATE column of AM_CERTIFICATE_METADATA is empty leading to the error scenario.
Fixed the issue by running the EP certificate migration(which copies certificate content as a blob to DB) before revision related migration step.
> Link(s) …
=> [4.0.0] Place certificate migration before revision related migration

migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom320.java
This PR fixes https://github.com/wso2/api-manager/issues/633 …
=> Fix wsdl archive migration issue

components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/v400/V400RegistryResourceMigrator.java
Fixes https://github.com/wso2/api-manager/issues/633 for 4.1.0
=> Add wsdl archive fixes

components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/v400/V400RegistryResourceMigrator.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/utils/Utils.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/validators/V410Validator.java
This PR adds migration fixes from APIM 4.1.0 migration resources …
=> Add migration fixes from 4.1.0

migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom320.java
Fixes https://github.com/wso2/api-manager/issues/706 …
=> [4.0.0] Skip revision deployment if no gateway env ('none') is configured

migration-client/wso2-api-migration-client/buildNumber.properties, migration-client/wso2-api-migration-client/pom.xml
Reverts,
[1]. https://github.com/wso2-extensions/apim-migration-resources/pull/251
[2]. https://github.com/wso2-extensions/apim-migration-resources/pull/252
[3]. https://github.com/wso2-extensions/apim-migration-resources/pull/256
> Link(s) to product documentation that addresses the …
=> [4.0.0]Revert PRs #251, #252 and #256

migration-client/wso2-api-migration-client/buildNumber.properties, migration-client/wso2-api-migration-client/pom.xml
Fix Jenkins build failure and remove build number plugin
=> remove build number plugin to fix jenkins build failure

migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom320.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/utils/Utils.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/validators/V400Validator.java
This PR fixes the issues in pre validation client for APIM migration.  …
=> Add fixes for pre validation client

components/migration-client/wso2-api-migration-client/src/main/resources/rxts/4.2.0/api.rxt
##Purpose
Add missing api.rxt for 4.2.0 to migration client
Fixing: https://github.com/wso2/api-manager/issues/911
=> Add missing api rxt for 4.2.0

components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/ExtendedAPIMConfigServiceImpl.java
Fix issue with the tenant-conf not returned in the `ExtendedAPIMConfigServiceImpl`
=> Fix issue with the tenant-conf not returned

components/migration-client/wso2-api-migration-client/src/assembly/dist.xml
Add 4.2.0 rxt to migration resources
=> Add 4.2.0 rxt to migration resources

migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom18to19.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom310.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom320.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateUUIDToDB.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/ValidationHandler.java
> Fixes https://github.com/wso2/api-manager/issues/1103 by handling null pointers
> Link to the PR for changes to the training …
=> Fix inactive tenant migration issue

migration-client/wso2-api-migration-client/pom.xml
=> Prepare for next 4.0.0.4 release
