migration-client/wso2-api-migration-client/pom.xml, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/APIMMigrationService.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom110to200.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom18to19.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom19to110.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom200.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom200to210.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom210.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrationClient.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/ScopeRoleMappingPopulationClient.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/sp_migration/APIMStatMigrationClient.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/dao/SharedDAO.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/dto/UserRoleFromPermissionDTO.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/Constants.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/RegistryServiceImpl.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/SharedDBUtil.java
In API Manager 3.1.0, login flow is changed with role base access control where user should have respective roles to access Publisher and Developer Portal. Since 3.1.0 UI depends completely on REST APIs, authentication to access different components solely depends on the scope-role mapping defined in registry file tenant-conf.json.
By default, the scope-role mapping is added only for the internal roles such as Internal/publisher, Internal/creator and Internal/subscriber. If there are any custom roles defined for API Creator, API Publisher, API Subscriber and Admin, those roles should be configured under relevant scopes. Currently, we suggest to do this manually, but if a particular customer has a large number of roles this might be a tedious task to do.
So, the purpose of this PR is to …
=> Modifying the migration client of APIM 3.1.0 to populate "RoleMappings" in tenant-conf.json

migration-client/wso2-api-migration-client/pom.xml, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/APIMMigrationService.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom110to200.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom18to19.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom19to110.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom200.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom200to210.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom210.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrationClient.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/ScopeRoleMappingPopulationClient.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/sp_migration/APIMStatMigrationClient.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/dao/SharedDAO.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/dto/UserRoleFromPermissionDTO.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/Constants.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/RegistryServiceImpl.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/SharedDBUtil.java
In API Manager 3.2.0, login flow is changed with role base access control where user should have respective roles to access Publisher and Developer Portal. Since 3.2.0 UI depends completely on REST APIs, authentication to access different components solely depends on the scope-role mapping defined in registry file tenant-conf.json.
By default, the scope-role mapping is added only for the internal roles such as Internal/publisher, Internal/creator and Internal/subscriber. If there are any custom roles defined for API Creator, API Publisher, API Subscriber and Admin, those roles should be configured under relevant scopes. Currently, we suggest to do this manually, but if a particular customer has a large number of roles this might be a tedious task to do.
So, the purpose of this PR is to …
=> Modifying the migration client of APIM 3.2.0 to populate "RoleMappings" in tenant-conf.json

migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/dao/SharedDAO.java
Fixes: https://github.com/wso2/product-apim/issues/8594
Conduct scope role migration without errors based on the database type
Changed the **setString** function in SharedDao.java to **setInt** to eliminate errors which occur due to various database types (eg:- postgres). 
- JDK 1.8.0_251
- Ubuntu 20.04 LTS
=> [3.1.0] Fixing scope role mapping error in migration client

migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom210.java
Removing rxt migration from 3.2.0 migration client as this is not required.
=> Remove RXT migration from APIM 3.2.0 client

migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/ScopeRoleMappingPopulationClient.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/dao/SharedDAO.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/Constants.java
Fixes: https://github.com/wso2/product-apim/issues/9003
Update the migration client by adding the functionality to populate scope role mapping for custom admin roles and add those to the tenant-conf.json of each tenant.
For each tenant,
1. Retrieved the **admin user role names** and **domain names** for the permissions '/permission/admin/manage/apim_admin', '/permission/admin/manage/', '/permission/admin/manage', '/permission/admin/', '/permission/admin', '/permission/', '/permission'.
2. As done in https://github.com/wso2-extensions/apim-migration-resources/pull/10, updated the **RoleMappings** field with admin and the corresponding role names retrieved in the above step.
Example:- 
```
"RoleMappings": {
"Internal/creator": "Internal/creator,testrole1,testrole2",
"Internal/publsher": …
```
=> Modifying the migration client of APIM 3.2.0 to populate "RoleMappings" with admin role mappings

migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/Constants.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/RegistryServiceImpl.java
Fixes: https://github.com/wso2/product-apim/issues/9076
Assigning the correct type "SOAPTOREST" to the registry resource.
- Modified the registry migration client to check whether a particular API is a SOAPTOREST API.
- If so the overview_type of the registry resource was set to "SOAPTOREST".
SOAP to REST conversion logs are visible in the resources in Publisher portal after the migration.
- jdk 1.8.0_251
- Ubuntu 20.04 LTS
- PostgreSQL 12.3
=> [3.2.0 Migration] Assigning the correct type to SOAPTOREST APIs during the registry migration

migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/dao/APIMgtDAO.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/dao/SharedDAO.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/Constants.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/RegistryServiceImpl.java
Fixes: https://github.com/wso2/product-apim/issues/9083
Adding the URI templates required when invoking WebSocket APIs.
- Modified the registry migration client to check whether a particular API is a WS API.
- If so, the URL mappings were added to AM_API_URL_MAPPING tables for that particular API.
Users can invoke migrated WS APIs.
- jdk 1.8.0_251
- Ubuntu 20.04 LTS
- PostgreSQL 12.3
- wscat version: 4.0.1
=> [3.2.0 Migration] Adding the missing URL mappings that are required to invoke WS APIs

migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/APIMMigrationService.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom110to200.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom18to19.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom19to110.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom200.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom200to210.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom210.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom310.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrationClient.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/ScopeRoleMappingPopulationClient.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/sp_migration/APIMStatMigrationClient.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/dao/APIMgtDAO.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/Constants.java
Adding cross tenant subscription validation. With this the migrations to APIM 3.2 will be aborted if cross tenant subscriptions are found. 
To ignore the validation result and proceed with migration, set the flag `ignoreCrossTenantSubscriptions` to true as below
`sh wso2server.sh -DmigrateFromVersion=3.1.0 -DignoreCrossTenantSubscriptions=true`
=> Add cross tenant susbcription validation

migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/ScopeRoleMappingPopulationClient.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/dao/SharedDAO.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/Constants.java
Fixes: https://github.com/wso2/product-apim/issues/9003
Backporting https://github.com/wso2-extensions/apim-migration-resources/pull/45
Update the migration client by adding the functionality to populate scope role mapping for custom admin roles and add those to the tenant-conf.json of each tenant.
For each tenant,
1. Retrieved the **admin user role names** and **domain names** for the permissions '/permission/admin/manage/apim_admin', '/permission/admin/manage/', '/permission/admin/manage', '/permission/admin/', '/permission/admin', '/permission/', '/permission'.
2. As done in https://github.com/wso2-extensions/apim-migration-resources/pull/10, updated the **RoleMappings** field with admin and the corresponding role names retrieved in the above step.
Example:- 
```
"RoleMappings": { …
```
=> Modifying the migration client of APIM 3.1.0 to populate "RoleMappings" with admin role mappings

migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/Constants.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/RegistryServiceImpl.java
Fixes: https://github.com/wso2/product-apim/issues/9076
Backporting https://github.com/wso2-extensions/apim-migration-resources/pull/50
Assigning the correct type "SOAPTOREST" to the registry resource.
- Modified the registry migration client to check whether a particular API is a SOAPTOREST API.
- If so the overview_type of the registry resource was set to "SOAPTOREST".
SOAP to REST conversion logs are visible in the resources in Publisher portal after the migration.
- jdk 1.8.0_251
- Ubuntu 20.04 LTS
- PostgreSQL 12.3
=>  [3.1.0 Migration] Assigning the correct type to SOAPTOREST APIs during the registry migration

migration-client/wso2-api-migration-client/buildNumber.properties, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom200.java
This PR updates migration client to add DefaultRoleCreation configuration to tenant-conf.json when migrating from 2.0.0
Fixes https://github.com/wso2/product-apim/issues/9603.
=> Update migration client to add DefaultRoleCreation configuration to tenant-conf.json

migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/RegistryServiceImpl.java
Fixes the migration problem to APIM 3.2.0 by fixing the checking done to see if the overview type is null.
Cherry-pick the commits of [1].
[1] https://github.com/wso2-extensions/apim-migration-resources/pull/69
=> [3.2.0] Fixing the check done to see if the overview type is null

migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/APIMMigrationService.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom320.java
- Do migrations for All other versions (APIM 2.5, 2.6, 3.0, 3.1)
- Append protocol if labels access URL does not contain the protocol (in APIM versions other than 3.2.0 is not validating the label's access URL, the user could be given the full access URL [i.e. https://mg.wso2.com] or just host only [i.e. mg.wso2.com])
Tested with APIM 2.5 to APIM 4.0 migration
https://github.com/wso2/product-apim/issues/10151
=> Label - Vhost migration for APIM 2.5, 2.6, 3.0, 3.1

migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/APIMMigrationService.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom320.java
Remove the following fault handlers from fault sequences when migrating to APIM 4.0.0
1. org.wso2.carbon.apimgt.usage.publisher.APIMgtFaultHandler
2. org.wso2.carbon.apimgt.gateway.handlers.analytics.APIMgtFaultHandler
Fixes: https://github.com/wso2/product-apim/issues/10238
https://github.com/wso2/carbon-apimgt/pull/10136
=> Remove Unnecessary Fault Handlers from Fault Sequences when Migrating to APIM 4.0.0

migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/APIMMigrationService.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom110to200.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom18to19.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom19to110.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom200.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom200to210.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom210.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom310.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrationClient.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/ScopeRoleMappingPopulationClient.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/sp_migration/APIMStatMigrationClient.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/dao/APIMgtDAO.java
The block conditions on 2.x versions are stored as follows.
The block conditions on 3.2.0 versions are stored as follows.
When migration occurs the VALUE of these tables gives an issue. This PR will fix that issue to edit the values of the VALUE column of 2.x versions into JSON format.
=> [3.2.0] Update migration client to support IP based block conditions when migrating from 2.x versions to 3.2.0

migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/RegistryServiceImpl.java
$Subject
Properties added without the display in the developer portal before migration are visible in-store after migration.
=> Resolve concurrent modification exception in resource map

components/migration-client/wso2-api-migration-client/src/main/resources/build-migration-script.sh
This PR fixes the issue in script to generate db migration from APIM 2.6.0 to 4.x.
=> Fix issue in build-migration-script.sh of 2.6.0 to 4.x

migration-client/wso2-api-migration-client/buildNumber.properties, migration-client/wso2-api-migration-client/pom.xml, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/APIMMigrationService.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/ApplicationOwnerChangeManagementClient.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/dao/APIMgtDAO.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/dto/ApplicationDetailsDTO.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/Constants.java
This option is used to update the SP APP name, Role Name, and IDN Application name if the owner of the Application is transferred. 
From APIM 3.2.0, when we transfer the ownership of an application, SP Name, Role Name changes with the transferred user. Eg: If the Application name is PizzaApp created by user chris, SP app name would be chris_PizzaApp_Production and the role associated with that app would be Application/chris_PizzaApp_Production. 
Once we transfer this to kim user, before 3.x, owner transfer happens, but we don not update the created application names or role names. 
From 3.2.0 onwards, we update these such that SP app would be changed to kim_PizzaApp_Production and role to Application/kim_PizzaApp_Production.
With this flow, we will query the tables and regenerate the …
=> Add the app owner rewrite option when migrating from 2.x to 3.2.0

components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/APIUtil.java
Fixes below issues during APIM migration.
```
[2022-05-27 03:51:18,077] ERROR - ApiMgtDAO Unable to find the API with UUID : creator_user-AT-abc1.com-HelloAPI-1.0 in the database
org.wso2.carbon.apimgt.migration.APIMigrationException: Unable to migrate api metadata definition of API : HelloAPI-1.0-creator_user-AT-abc1.com
at org.wso2.carbon.apimgt.migration.migrator.v410.V410RegistryResourceMigrator.registryDataPopulation(V410RegistryResourceMigrator.java:129)
at org.wso2.carbon.apimgt.migration.migrator.v410.V410RegistryResourceMigrator.migrate(V410RegistryResourceMigrator.java:51)
at org.wso2.carbon.apimgt.migration.migrator.client.V410Migration.migrate(V410Migration.java:52)
at org.wso2.carbon.apimgt.migration.APIMMigrationClient.completedServerStartup(APIMMigrationClient.java:67)
at …
```
=> [4.1.0-migration] Fix getID issue in API migration

components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/dao/APIMgtDAO.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/v400/V400DBDataMigrator.java
This PR fixes the following issue that comes up when trying to generate keys for migrated apps. This happens because the key managers are not being properly migrated in 3.1.0 to 3.2.0 migration step.
```
"[2022-06-04 20:01:36,654] ERROR - GlobalThrowableMapper An unknown exception has been captured by the global exception mapper.
java.lang.NullPointerException: null
at org.wso2.carbon.apimgt.impl.APIConsumerImpl.getApplicationKeyByAppIDAndKeyMapping_aroundBody244(APIConsumerImpl.java:5513) ~[org.wso2.carbon.apimgt.impl-9.20.74.10-SNAPSHOT.jar:?]
at org.wso2.carbon.apimgt.impl.APIConsumerImpl.getApplicationKeyByAppIDAndKeyMapping(APIConsumerImpl.java:5506) ~[org.wso2.carbon.apimgt.impl-9.20.74.10-SNAPSHOT.jar:?]
at org.wso2.carbon.apimgt.rest.api.store.v1.impl.ApplicationsApiServiceImpl.get …
```
=> [4.1.0 - Migration] Fix issues with KM migration from 3.1.0 to 3.2.0

components/migration-client/wso2-api-migration-client/pom.xml, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/client/V320Migration.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/v320/IdentityScopeMigrator.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/v320/dao/ApiMgtDAO.java
Adds the identity scope migrator for the migration from APIM 3.1.0 to 3.2.0
This migrator will be used to migrate the local scopes from `IDN_OAUTH2_SCOPE` table to the new `AM_SCOPE` table when migrating from APIM 3.1.0 to 3.2.0
=> [4.1.0 - Migration] Add identity scope migrator for 3.1.0 to 3.2.0 migration

components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/Constants.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/ValidationHandler.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/dao/ApiMgtDAO.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/validators/V410Validator.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/validators/Validator.java
- Add a new validator to validate the availability of the APIs in the database. This is done by comparing the API artifacts in the registry with the API entries in the database.
- Update the validator flow to run all available validators or selected validators. If the user gives `-DrunPreMigration` only, all the available validators will be run. If its given as `-DrunPreMigration=apiDefinitionValidation`, only the API definition validator will be run.
=> [4.1.0 - Migration] Add a validator to check API availability

components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/Constants.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/utils/Utils.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/validators/V410Validator.java
This adds the capability to save the invalid swagger definitions during the migration pre-validation step. 
`-DsaveInvalidDefinition` flag can be used to enable this during the pre-validation step. This will save the relevant swagger definitions to the `definitions` directory in `migration-resources` in the `<API_UUID>.json` format.
Sample command
```
sh api-manager.sh -Dmigrate -DmigrateFromVersion=2.6.0 -DmigratedVersion=4.1.0 -DrunPreMigration=apiDefinitionValidation -DsaveInvalidDefinition
```
=> [4.1.0] Add capability to save invalid swaggers during pre-migration

components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/Constants.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/ValidationHandler.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/dao/ApiMgtDAO.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/dao/constants/SQLConstants.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/validators/V410Validator.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/validators/Validator.java
Add api resource level auth scheme pre-validation step for older 2.x versions as 'Application' & ' Application_User' auth schemes are not supported anymore.
Fixing https://github.com/wso2/api-manager/issues/601
Warnings will be displayed for api resources using the unsupported auth schemes
2.6.0 to 4.1.0 migrations were done on MySQL, PostgreSQL
=> Add api resource level auth scheme prevalidation step

components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/v400/V400RegistryResourceMigrator.java
Issue - an error is displayed when api is visited on publisher portal after migration, when the gateway environment of the published API is configured as 'none' 
Skips revision deployment when the gateway is configured as 'none'
=> [4.1.0] Skip revision deployment if no gateway env ('none') is configured

migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/Constants.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/ValidationHandler.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/dao/ApiMgtDAO.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/dao/SQLConstants.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/validators/V400Validator.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/validators/Validator.java
Add api resource level auth scheme pre-validation step for older 2.x versions as 'Application' & ' Application_User' auth schemes are not supported anymore.
Fixing https://github.com/wso2/api-manager/issues/601
Warnings will be displayed for api resources using the unsupported auth schemes
=> [4.0.0] Add api resource level auth scheme prevalidation step

components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/Constants.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/ValidationHandler.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/dao/ApiMgtDAO.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/dao/constants/SQLConstants.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/validators/V410Validator.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/validators/Validator.java
Add api resource level auth scheme pre-validation step for older 2.x versions as 'Application' & ' Application_User' auth schemes are not supported anymore.
Fixing https://github.com/wso2/api-manager/issues/601
Warnings will be displayed for api resources using the unsupported auth schemes
=> [4.x.x] Add api resource level auth scheme prevalidation step

components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/Constants.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/ValidationHandler.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/dao/ApiMgtDAO.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/dao/constants/SQLConstants.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/dto/ApplicationDTO.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/dto/ApplicationKeyMappingDTO.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/validators/ApplicationValidator.java
Third party key manager interfaces have changes in new versions and may need to be reconfigured.
https://github.com/wso2/api-manager/issues/607#issue-1334421778
Warn users about the changes to do necessary configurations.
Retrieve all applications and check is keys are generated. If keys are generated check IDN_OAUTH_CONSUMER_APPS by CONSUMER_KEY. If the record is empty then third party key manager is used for the application and a warning is displayed at pre-migration. 
2.6.0 to 4.1.0 migrations were done on MySQL 8.0.30, PostgreSQL 14.6
=> Add Prevalidation step to warn about third party key-manager usage

components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/v400/V400RegistryResourceMigrator.java
Issue - an error is displayed when api is visited on publisher portal after migration, when the gateway environment of the published API is configured as 'none' 
fixing https://github.com/wso2/api-manager/issues/706
Skips revision deployment when the gateway is configured as 'none'
=> [4.x.x] Skip revision deployment if no gateway env ('none') is configured

components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/Constants.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/ValidationHandler.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/dao/ApiMgtDAO.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/dao/constants/SQLConstants.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/dto/ApplicationDTO.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/dto/ApplicationKeyMappingDTO.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/validators/ApplicationValidator.java
Third party key manager interfaces have changes in new versions and may need to be reconfigured.
Fixing https://github.com/wso2/api-manager/issues/607#issue-1334421778
Warn users about the changes to do necessary configurations.
Retrieve all applications and check is keys are generated. If keys are generated check IDN_OAUTH_CONSUMER_APPS by CONSUMER_KEY. If the record is empty then third party key manager is used for the application and a warning is displayed at pre-migration.
=> [4.x.x] Add Prevalidation step to warn about third party key-manager usage

migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/Constants.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/ValidationHandler.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/dao/ApiMgtDAO.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/dao/SQLConstants.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/dto/ApplicationDTO.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/dto/ApplicationKeyMappingDTO.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/validators/ApplicationValidator.java
Third party key manager interfaces have changes in new versions and may need to be reconfigured.
Fixing https://github.com/wso2/api-manager/issues/607#issue-1334421778
Warn users about the changes to do necessary configurations.
Retrieve all applications and check is keys are generated. If keys are generated check IDN_OAUTH_CONSUMER_APPS by CONSUMER_KEY. If the record is empty then third party key manager is used for the application and a warning is displayed at pre-migration. 
2.6.0 to 4.0.0 migrations were done on MySQL 8.0.30, PostgreSQL 14.6
=> [4.0.0] Add Prevalidation step to warn about third party key-manager usage

components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/Constants.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/ValidationHandler.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/validators/V410Validator.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/validators/Validator.java
If deployed gateway of an api is 'none' it gives an error after migration in the publisher portal.
Issue : https://github.com/wso2/api-manager/issues/706
It was fixed by skipping revision deployment for such APIs
Fix: #277 
This pre-validator warns the user while migration, about APIs with gateway type set to none.
Fixing : https://github.com/wso2/api-manager/issues/747
Warn the user that API revision deployment will be skipped, if the gateway environment type of the API is set to 'none'.
#277
=> [4.x.x] Add pre-validation step to validate api deployed gateway type is not 'none'

components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/Constants.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/ValidationHandler.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/validators/V410Validator.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/validators/Validator.java
If deployed gateway of an api is 'none' it gives an error after migration in the publisher portal.
Issue : https://github.com/wso2/api-manager/issues/706
It was fixed by skipping revision deployment for such APIs
Fix: #269
This pre-validator warns the user while migration, about APIs with gateway type set to none.
Fixing : https://github.com/wso2/api-manager/issues/747
Warn the user that API revision deployment will be skipped, if the gateway environment type of the API is set to 'none'.
#269
=> [4.1.0] Add pre-validation step to validate api deployed gateway type is not 'none'

migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/Constants.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/ValidationHandler.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/validators/V400Validator.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/validators/Validator.java
If deployed gateway of an api is 'none' it gives an error after migration in the publisher portal.
Issue : https://github.com/wso2/api-manager/issues/706
It was fixed by skipping revision deployment for such APIs
Fix: #267 
This pre-validator warns the user while migration, about APIs with gateway type set to none.
Fixing : https://github.com/wso2/api-manager/issues/747
Warn the user that API revision deployment will be skipped, if the gateway environment type of the API is set to 'none'.
#267
=> [4.0.0] Add pre-validation step to validate api deployed gateway type is not 'none'

components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/v300/V300RegistryResourceMigrator.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/v320/V320DBDataMigrator.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/v320/V320RegistryResourceMigrator.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/v400/V400DBDataMigrator.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/v400/V400RegistryResourceMigrator.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/utils/Utils.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/validators/APIValidator.java
When migrations fail due to errors, only the first occurrence is identified due to exiting tenant/artefact wise iterations. Exception handling is needed to be modified to continue on errors to identify all errors at once.
Fixing : https://github.com/wso2/api-manager/issues/615
Fixing : https://github.com/wso2/api-manager/issues/801
Fixing : https://github.com/wso2/api-manager/issues/802
Identify all errors in one migration attempt.
Exceptions thrown within an iteration is caught and logged without exiting the loop. 
Error state is maintained and logged at the end.
#254 
#300
=> [4.1.0] Modify exception handling to continue migration on errors

migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom310.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom320.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateUUIDToDB.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrationClientBase.java
When migrations fail due to errors, only the first occurrence is identified due to exiting tenant/artefact wise iterations. Exception handling is needed to be modified to continue on errors to identify all errors at once.
Fixing : https://github.com/wso2/api-manager/issues/615
Identify all errors in one migration attempt.
Exceptions thrown within an iteration is caught and logged without exiting the loop. 
Error state is maintained and logged at the end.
#254 
#304 
#306
=> [4.0.0] Modify exception handling to continue migration on errors

components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/v300/V300RegistryResourceMigrator.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/v320/V320DBDataMigrator.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/v320/V320RegistryResourceMigrator.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/v400/V400DBDataMigrator.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/v400/V400RegistryResourceMigrator.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/utils/Utils.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/validator/validators/APIValidator.java
When migrations fail due to errors, only the first occurrence is identified due to exiting tenant/artefact wise iterations. Exception handling is needed to be modified to continue on errors to identify all errors at once.
Fixing : https://github.com/wso2/api-manager/issues/615
Fixing : https://github.com/wso2/api-manager/issues/801
Fixing : https://github.com/wso2/api-manager/issues/802
Identify all errors in one migration attempt.
Exceptions thrown within an iteration is caught and logged without exiting the loop. 
Error state is maintained and logged at the end.
#254 
#304 
#307 
#300
=> [4.x.x] Modify exception handling to continue migration on errors

components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/v420/V420RegistryResourceMigrator.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/Constants.java
> Migrate LifeCycle config from registry to Advance Configuration
> This fixes wso2/api-manager#364
> Migration Fix for the wso2/api-manager#314
1. Read the LifeCycle.xml file in each tenant and convert that to a respective LifeCycle Object.
2. Add the converted lifecycle object to tenant-conf.json(or Advanced Configuration of the tenant)
3. Detach the APILifeCycle from the Registry	
4. Pre-validation to validate whether lcState is same as the overview_status of the API
=> LifeCycle Migrations added

components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/v400/V400RegistryResourceMigrator.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/util/APIUtil.java, pom.xml
The following error is raised as deprecated `setUUID` method doesn't exist in the newer versions of carbon-apimgt.
Therefore the version was updated along with new `setUuid` method.
```
[2022-11-23 14:01:51,201] ERROR - Framework FrameworkEvent ERROR
java.lang.NoSuchMethodError: 'void org.wso2.carbon.apimgt.api.model.APIProductIdentifier.setUUID(java.lang.String)'
at org.wso2.carbon.apimgt.migration.migrator.v400.V400RegistryResourceMigrator.addAPIProductRevision(V400RegistryResourceMigrator.java:700) ~[org.wso2.carbon.apimgt.migrate.client-4.2.0.20-SNAPSHOT.jar:?]
at org.wso2.carbon.apimgt.migration.migrator.v400.V400RegistryResourceMigrator.apiRevisionRelatedMigration(V400RegistryResourceMigrator.java:476) ~[org.wso2.carbon.apimgt.migrate.client-4.2.0.20-SNAPSHOT.jar:?]
at …
```
=> Bump carbon apimgt verion and update depricated setUUID method

components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/client/V410Migration.java, components/migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/migrator/client/V420Migration.java
Setting ExtendedAPIMConfigService as disabled. This extended implementation is only needed and enabled for migrations which are coming from versions before APIM 4.1.0
Also need to disable this for future migrations such as from APIM 4.2.0 to APIM 4.3.0
i.e. : add it to `V420Migration`, `V430Migration`, `V440Migration` so on.
=> [4.2.0] Disable ExtendedAPIMConfigService for 4.2.0 onwards

migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom310.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateFrom320.java, migration-client/wso2-api-migration-client/src/main/java/org/wso2/carbon/apimgt/migration/client/MigrateUUIDToDB.java
Add logs when artifact migration for tenant skipped due to no API artifacts found in registry.
Related to fix done for https://github.com/wso2/api-manager/issues/1103
=> Add logs when artifact migration for tenant skipped
